theme: minima
title: Quite random
description: "Far Out in the uncharted backwaters of the unfashionable end of the Western Spiral arm of the galaxy lies a small unregarded yellow sun"

header_pages:
  - about.md
  - apps.md
  - books.md

# You can add more configuration options here as needed